### ISSUE TITLE
ShowMoreTextView is not available on 1.0.1 version.

### ISSUE THREAD

**Issue by ghost** [aayush287/ShowMoreTextView#1]
Hi, Thanks for providing such a good featured solution.

I think I found some bug in 1.0.1 version.

Declaring coding.universe.showmoretextview.ShowMoreTextView in xml works well in 1.0.0 version, But not in 1.0.1

It could be my mistake. 

Thanks for reading :)

**Comment by thearchetypee** [comment]
@hkg5600 Thanks for reporting the issue. It has been fixed.
